markdown: kramdown
highlighter: none
permalink: pretty
encoding: utf-8
port: 4009
main_baseurl: https://bitwarden.com

sass:
  sass_dir: ./_scss
  style: compressed

exclude:
  - node_modules
  - bitwarden-help.sln
  - package.json
  - package-lock.json
  - gulpfile.js
  - appveyor.yml
  - README.md

include:
  - '.nojekyll'

collections:
  categories:
    output: true
    permalink: /:path/
    order:
      - getting-started.md
      - account-management.md
      - send.md
      - import-export.md
      - auto-fill.md
      - two-step-login.md
      - hosting.md
      - organizations.md
      - providers.md
      - directory-connector.md
      - login-with-sso.md
      - security.md
      - plans-and-pricing.md
      - business.md
      - miscellaneous.md
  articles:
    output: true
    permalink: /article/:name/

plugins:
  - jekyll-redirect-from
